### ISSUE TITLE
Noise3D pixelization bug [?]

### ISSUE THREAD

**Issue by jijjijj** [stegu/webgl-noise#11]
Hi, I use the simplex noise 3d in my work. I noticed that the higher time you give the more pixelized the image becomes:

Time = 0.3:
![image](https://github.com/stegu/webgl-noise/assets/24494830/429254b7-fafa-4057-95d9-61c7a7c62ce1)
Time = 2313.0 (with zoomed image)
![image](https://github.com/stegu/webgl-noise/assets/24494830/55f66ae6-50fd-4e68-818f-5a6475412708)
Time = 9000000.0
![image](https://github.com/stegu/webgl-noise/assets/24494830/539307de-2353-42c5-90c5-ed649a3e8071)

Is there any way to fix it?

**Comment by jijjijj** [comment]
It seems it also happens with big x, y coordinates

**Comment by stegu** [comment]
This is a problem with all noise functions. A 32-bit float loses its
fractional bits as the numbers get higher. At around 8 million, you only
get integers, from 16 million you get only even integers, and so on.
So, no fix other than moving to 64-bit double precision, which is slower on
all current platforms and not even supported on low end hardware.
Wrap your coordinates to reasonable numbers to dodge the problem. The
function is periodic, so it's possible to restrict yourself. If you want a
specific period, consider using my more recent creation "psrdnoise", also
on Github.

  /Stefan G


Den tors 25 jan. 2024 22:18jijjijj ***@***.***> skrev:

**Comment by jijjijj** [comment]
Got it, thank you for your response
