### ISSUE TITLE
Compilation Error (NVidia): implicit cast from 'float' to 'vec3'

### ISSUE THREAD

**Issue by john-chapman** [stegu/webgl-noise#2]
psrdnoise2D.glsl fails to compile (on NVidia at least) because the call to permute() on line 91 contains an implicit cast from 'float' to 'vec3' - adding a single-float overload for permute() and mod289() solves the issue.

**Comment by stegu** [comment]
Oups. I don't know how I could have let that stupid mistake slip.
Thanks for doing the testing which I obviously forgot to do!
The code is now updated.

**Comment by stegu** [comment]
Closing the issue.
